privkey = "0xdc18f3406f654b1e07f71943736e4ee2342b17f0185fa0c3bd45d6423290d64c"
data_path = "/app/devtools/chain/data"

[graphql]
listening_address = "0.0.0.0:8003"
graphql_uri = "/graphql"
graphiql_uri = "/graphiql"
workers = 0
maxconn = 25000
max_payload_size = 1048576

[network]
listening_address = "0.0.0.0:1340"
rpc_timeout = 10
[[network.bootstraps]]
pubkey = "0x035cbdb9a9617a011cd780c036da0ac8641b681803bbfefdda207806de856df321"
address = "173.20.0.21:1337"

[mempool]
pool_size = 200000
broadcast_txs_size = 200
broadcast_txs_interval = 200

[executor]
light = false

[logger]
filter = "info"
log_to_console = true
console_show_file_and_line = false
log_path = "/app/devtools/chain/data/logs"
log_to_file = true
metrics = true
