# chain id
chain_id = "b6a4d7da21443f5e816e8700eea87610e6d769657d6b8ec73028457bf2ca4036"  # by sha256(Muta)

# crypto
privkey = "61b315af6f2c21a4716689e6b5fb65e0acdfda86f2e167d8ea1000b75372b90c"

# db config
data_path = "./devtools/chain/data"

[graphql]
listening_address = "0.0.0.0:8000"
graphql_uri = "/graphql"
graphiql_uri = "/graphiql"

[network]
listening_address = "0.0.0.0:1337"

[[network.bootstraps]]
pubkey = "03d158fb85df6201708f2cbde51e0b7c2d8835a28aaea7ed243e5db1aa442b18b1"
address = "172.20.0.11:1337"

[mempool]
timeout_gap = 200
pool_size = 20000

[consensus]
cycles_limit = 99999999
cycles_price = 1
interval = 3000
verifier_list = [ "10ecc2746d8ad8ca82872bf0af59ebefbe003b2d0c" ]

[consensus.duration]
propose_numerator = 24
propose_denominator = 30
prevote_numerator = 6
prevote_denominator = 30
precommit_numerator = 6
precommit_denominator = 30

[executor]
light = false
