language: rust
dist: bionic
sudo: false

# cache sccache and its cache
cache:
  apt: true
  directories:
    - $TRAVIS_HOME/.cargo/
    - $TRAVIS_HOME/.cache/sccache

git:
  depth: 1
  submodules: false

if: 'branch IN (master, develop, staging, trying) OR type != push OR fork = true OR tag =~ ^v'

addons:
  apt:
    packages:
    - gcc
    - librocksdb5.8
    - librocksdb-dev

matrix:
  include:
  - rust: nightly

install: ./devtools/ci/install.sh
script: ./devtools/ci/script.sh

# use sccache and limit cache size to 2G, so travis cache command dont timeout
env:
  global:
    - RUST_BACKTRACE=full
    - RUSTC_WRAPPER=sccache
    - SCCACHE_CACHE_SIZE="2G"
    - USE_SYS_ROCKSDB: true
    - FMT: true
    - CHECK: true
    - TEST: true

before_cache:
  - rm -rf "$TRAVIS_HOME"/.cargo/registry"

before_script:
  - git lfs pull
