[package]
name = "muta"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
common-config-parser = { path = "common/config-parser" }
common-logger = { path = "common/logger" }
common-cita = { path = "common/cita" }

components-jsonrpc = { path = "components/jsonrpc" }
components-database = { path = "components/database" }
components-executor = { path = "components/executor" }
components-transaction-pool = { path = "components/transaction-pool" }

core-crypto = { path = "core/crypto" }
core-runtime = { path = "core/runtime" }
core-storage = { path = "core/storage" }
core-types = { path = "core/types" }
core-consensus = { path = "core/consensus" }
core-context = { path = "core/context" }
core-pubsub = { path = "core/pubsub" }
core-network = { path = "core/network" }

hex = "0.3"
tokio = "0.1"
clap = "2.32"
log = "0.4"
num_cpus = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
futures01 = { package = "futures", version = "0.1" }
futures-preview = { version = "=0.3.0-alpha.14", features = [ "compat" ] }

[workspace]
members = [
  "common/cita",
  "common/config-parser",
  "common/logger",
  "common/channel",

  "core/types",
  "core/runtime",
  "core/consensus",
  "core/storage",
  "core/crypto",
  "core/merkle",
  "core/pubsub",
  "core/context",
  "core/network",
  "core/network/message",

  "components/transaction-pool",
  "components/database",
  "components/jsonrpc",
  "components/executor",
]
