[package]
name = "muta"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
config-parser = { path = "common/config-parser" }
logger = { path = "common/logger" }

# components-cita-jsonrpc = { path = "components/cita-jsonrpc" }
components-jsonrpc = { path = "components/jsonrpc" }
components-database = { path = "components/database" }
components-executor = { path = "components/executor" }
components-transaction-pool = { path = "components/transaction-pool" }
core-crypto = { path = "core/crypto" }
core-p2p = { path = "core/p2p" }
core-runtime = { path = "core/runtime" }
core-storage = { path = "core/storage" }
core-types = { path = "core/types" }
core-consensus = { path = "core/consensus" }
core-context = { path = "core/context" }

hex = "0.3"
futures = "0.1"
tokio = "0.1"
clap = "2.32"
log = "0.4"
num_cpus = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[workspace]
members = [
  "common/config-parser",
  "common/logger",

  "core/types",
  "core/runtime",
  "core/consensus",
  "core/storage",
  "core/p2p",
  "core/crypto",
  "core/merkle",
  "core/pubsub",
  "core/network",
  "core/context",

  "components/transaction-pool",
  "components/database",
  # "components/cita-jsonrpc",
  "components/jsonrpc",
  "components/executor",
]
