[package]
name = "core-merkle"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
core-types = { path = "../types" }

# static_merkle_tree = "1.0.0"
static_merkle_tree = { git = "https://github.com/yejiayu/static-merkle-tree.git", branch = "trait_scope" }
rlp = "0.3"
