[package]
name = "core-runtime"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
core-types = { path = "../types" }
core-crypto = { path = "../crypto" }
core-context = { path = "../context" }
core-serialization = { path = "../serialization" }

bytes = "0.4"
cita-vm = "0.1"
bft-rs = { git = "https://github.com/cryptape/bft-rs.git", features = [ "verify_req" ], branch = "bft_for_muta" }
