[package]
name = "core-runtime"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
core-types = { path = "../types" }
core-crypto = { path = "../crypto" }
core-context = { path = "../context" }

failure = "0.1"
futures = "0.1"
bytes = "0.4"
cita-vm = "0.1"
