[package]
name = "common-channel"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"
description = "crossbeam-channel wrapper with async/await support"

[dependencies]
crossbeam-channel = "0.3"
futures-preview = "0.3.0-alpha.14"
