[package]
name = "core-pubsub"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
futures-preview = { version = "0.3.0-alpha.16", features = [ "async-await", "nightly" ] }
uuid = { version = "0.7", features = [ "v4" ] }
log = "0.4"
