[package]
name = "database"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
core-runtime = { path = "../../core/runtime" }

failure = "0.1.3"
futures = "0.1.17"
futures-locks = "0.3"
