[package]
name = "protocol"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-preview = "0.3.0-alpha.18"
derive_more = "0.15"
async-trait = "0.1"
num-bigint = "0.2"
ethbloom = "0.6"
bytes = "0.4"
sha3 = "0.8"
hex = "0.3"
prost = "0.5"
serde = "1.0"
serde_derive = "1.0"
bincode = "1.1"
