[package]
name = "core-storage"
version = "0.1.0"
authors = ["Muta Dev <muta@nervos.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protocol = { path = "../../protocol" }

futures = "0.3"
derive_more = "0.15"
lazy_static = "1.4"
parking_lot = "0.9"
async-trait = "0.1"
rocksdb = "0.12"
bytes = "0.4"

[dev-dependencies]
num-traits = "0.2"
rand = "0.6"
hex = "0.3"
