[package]
name = "core-storage"
version = "0.1.0-alpha.0"
authors = ["Muta Dev <muta@nervos.org>"]
edition = "2018"
repository = "https://github.com/nervosnetwork/muta"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protocol = { path = "../../protocol", package = "muta-protocol" }

futures = "0.3"
derive_more = "0.15"
lazy_static = "1.4"
parking_lot = "0.10"
async-trait = "0.1"
rocksdb = "0.12"
tokio = { version = "0.2", features = [ "sync" ] }

[dev-dependencies]
num-traits = "0.2"
rand = "0.6"
hex = "0.4"
