[package]
name = "core-network"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protocol = { path = "../../protocol" }

async-trait = "0.1"
bincode = "1.1"
bytes = { version = "0.4", features = ["serde"] }
derive_more = "0.15"
futures-timer = "0.3"
futures-preview = { version = "0.3.0-alpha.19", features = [ "compat" ] }
generic-channel = { version = "0.2", features = [ "all" ] }
log = "0.4"
parking_lot = "0.9"
prost = "0.5"
rand = "0.7"
runtime = "0.3.0-alpha.7"
serde = "1.0"
serde_derive = "1.0"
snap = "0.2"
tentacle = { version = "0.2", features = [ "flatc" ] }
tentacle-ping = { version = "0.3", features = [ "flatc" ] }
tentacle-discovery = { version = "0.2", features = [ "flatc" ] }
hex = "0.4"

[dev-dependencies]
env_logger = "0.6"
runtime-tokio = "0.3.0-alpha.6"
quickcheck = "0.9"
quickcheck_macros = "0.8"
