[package]
name = "core-network"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
core-p2p = { path = "../p2p", features = ["prost-message"] }
core-types = { path = "../types" }
core-serialization = { path = "../serialization" }
core-context = { path = "../context" }
core-runtime = { path = "../runtime" }
core-pubsub = { path = "../pubsub" }

components-transaction-pool = { path = "../../components/transaction-pool" }

config-parser = { path = "../../common/config-parser" }

tentacle = "0.2.0-alpha.1"
log = "0.4"
futures = "0.1"
prost = "0.5"
bytes = "0.4"
serde_derive = "1.0"
serde = "1.0"
# TODO: rename futures01 instead
futures03 = { package = "futures-preview", version = "=0.3.0-alpha.14", features = [ "compat" ] }
uuid = "0.7"
parking_lot = "0.7"
tokio = "0.1"

[dev-dependencies]
env_logger = "0.6"
runtime = "0.3.0-alpha.1"
runtime-raw = "0.3.0-alpha.1"
runtime-tokio = "0.3.0-alpha.2"
