[package]
name = "core-network"
version = "0.1.0-alpha.0"
authors = ["Muta Dev <muta@nervos.org>"]
edition = "2018"
repository = "https://github.com/nervosnetwork/muta"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protocol = { path = "../../protocol", package = "muta-protocol" }

async-trait = "0.1"
bincode = "1.2"
derive_more = "0.99"
futures-timer = "2.0"
futures= { version = "0.3", features = [ "compat" ] }
hex = "0.4"
log = "0.4"
parking_lot = "0.10"
prost = "0.6"
bytes = "0.5"
rand = "0.7"
serde = "1.0"
serde_derive = "1.0"
snap = "0.2"
tentacle = { git = "https://github.com/zeroqn/p2p", branch = "muta", features = [ "flatc" ]}
tentacle-ping = { git = "https://github.com/zeroqn/p2p", branch = "muta", features = [ "flatc" ]}
tentacle-discovery = { git = "https://github.com/zeroqn/p2p", branch = "muta", features = [ "flatc" ]}
tentacle-identify = { git = "https://github.com/zeroqn/p2p", branch = "muta", features = [ "flatc" ]}
tokio = { version = "0.2", features = ["macros", "rt-core"]}

[dev-dependencies]
env_logger = "0.6"
quickcheck = "0.9"
quickcheck_macros = "0.8"
lazy_static = "1.4"

[features]
allow_global_ip = []

[[test]]
name = "broadcast"
path = "tests/gossip_test.rs"
required-features = [ "allow_global_ip" ]
