[package]
name = "core-network"
version = "0.2.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
common-channel = { path = "../../common/channel" }

core-network-message = { path = "./message" }
core-context = { path = "../context" }
core-serialization = { path = "../serialization" }
core-runtime = { path = "../runtime" }
core-types = { path = "../types" }

tentacle = "0.2"
tentacle-discovery = "0.2"
log = "0.4"
futures-preview = { version = "0.3.0-alpha.16", features = [ "compat", "async-await", "nightly" ] }
serde_derive = "1.0"
serde = "1.0"
rand = "0.6"
parking_lot = "0.8"
runtime = "0.3.0-alpha.4"
futures-timer = "0.2"
