[package]
name = "core-serialization"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
bytes = "0.4"
prost = "0.5"
prost-derive = "0.5"
futures-preview = { version = "0.3.0-alpha.13" }

core-types = { path = "../types" }

[build-dependencies]
prost-build = "0.5"
