data_path = "./devtools/chain/data/3"
privkey = "0x24ea3d9100f94f854f2c04863ddfd70542ff157bcb355bc842c092ada979b88b"

[network]
listening_address = "0.0.0.0:1339"
rpc_timeout = 10

[[network.bootstraps]]
peer_id = "QmZTHDCgo21skh7de1Newi66GyPzpuo7RhKcEZoKwSyY3F"
address = "localhost:1337" # Replace it with your IP

[graphql]
graphiql_uri = "/graphiql"
listening_address = "0.0.0.0:8002"
graphql_uri = "/graphql"
workers = 0 # if 0, uses number of available logical cpu as threads count.
maxconn = 25000
max_payload_size = 1048576

[executor]
light = false

[mempool]
broadcast_txs_size = 200
broadcast_txs_interval = 200
pool_size = 200000

[logger]
metrics = false
log_path = "./devtools/chain/logs/3"
log_to_console = true
filter = "info"
log_to_file = true
console_show_file_and_line = false

[rocksdb]
max_open_files = 64
