[package]
name = "core-network-message"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
core-types = { path = "../../types" }
core-serialization = { path = "../../serialization" }

bytes = "0.4"
prost = "0.5"
