[package]
name = "pool"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
muta = { path = "../../muta", features = ["with-grpc"] }
futures         = "0.1.25"
futures-cpupool = "0.1.8"
lazy_static = "1.2.0"
protobuf = "2.2.0"
