# crypto
privkey = "028590ad352d54387a9c8a0ecf7e180e68c4840c72f958fc5917657f506caa80"

# json rpc
rpc_address = "127.0.0.1:3030"
rpc_workers = 0

# db config
data_path = "./devtools/chain/rocksdb"

# transaction pool
pool_size = 100000
until_block_limit = 100
quota_limit = 9999999999

# consensus
consensus_tx_limit = 30000
consensus_interval = 3000
consensus_verifier_list = [ "19e49d3efd4e81dc82943ad9791c1916e2229138" ]
consensus_wal_path = "./devtools/chain/bft_wal"
