# Default values for deploy-chaos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

benchmark:
  schedule: "*/6 * * * *"
  image: mutadev/muta-benchmark:v0.1.12
  args:
    - -d
    - 300s
    - -c
    - 16
    - -g
    - 9999
    - cpu
    - 3

namespace: mutadev

repo_name: muta
version: latest

resources:
  cpu: 1100m
  memory: 4Gi
  storage: 6Gi
  persistent: true

chaos:
  - all

size: 4

chain_config:
  network:
    rpc_timeout: 10
  mempool:
    pool_size: 20000
    broadcast_txs_size: 200
    broadcast_txs_interval: 200

chain_genesis:
  prevhash: 0x44915be5b6c20b0678cf05fcddbbaa832e25d7e6ac538784cd5c24de00d47472
  metadata:
    chain_id: 0xb6a4d7da21443f5e816e8700eea87610e6d769657d6b8ec73028457bf2ca4036
    timeout_gap: 9999
    cycles_limit: 99999999
    cycles_price: 1
    interval: 3000
    propose_ratio: 15
    prevote_ratio: 15
    precommit_ratio: 10
    brake_ratio: 3
    tx_num_limit: 10000
    max_tx_size: 1073741824
  services:
    - name: asset
      payload: { "id": "0xf56924db538e77bb5951eb5ff0d02b88983c49c45eea30e8ae3e7234b311436c", "name": "MutaToken", "symbol": "MT", "supply": 320000011, "issuer": "muta14e0lmgck835vm2dfm0w3ckv6svmez8fdgdl705" }
