[package]
name = "keypair"
version = "0.1.0"
authors = ["zero.qn <zero.qn@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protocol = { path = "../../protocol" }

hex = "0.4"
rand = "0.7"
tentacle-secio = { version = "0.1", features = [ "flatc" ] }
