# crypto
privkey = "028590ad352d54387a9c8a0ecf7e180e68c4840c72f958fc5917657f506caa81"

# db config
data_path = "./devtools/chain/data"

[rpc]
address = "0.0.0.0:3030"
workers = 20
payload_size = 8388608

[network]
# private_key = "bcfa6d5fffa63edf3bd17b17422e416f9374d981322c4ccccf38de215e659b02"
bootstrap_addresses = ['192.168.0.35:1337']
listening_address = "0.0.0.0:1337"
max_connections = 40
send_buffer_size = 104857600
recv_buffer_size = 104857600

[txpool]
pool_size = 180000
until_block_limit = 10000
quota_limit = 1800000000

[consensus]
tx_limit = 60000
interval = 1000
verifier_list = [ "7899EE7319601cbC2684709e0eC3A4807bb0Fd74", "C5b874618a1E81C68bEb30A7A219Fee3f9839a01", "9Ad301Eb2A4938070ccda5e4b298C4f867812d6e", "64EC8878182F52af52611dDc575E267ABd012560" ]
# verifier_list = [ "7899EE7319601cbC2684709e0eC3A4807bb0Fd74", "C5b874618a1E81C68bEb30A7A219Fee3f9839a01", "9Ad301Eb2A4938070ccda5e4b298C4f867812d6e" ]
[synchronzer]
broadcast_status_interval = 180000

[rocksdb]
# 1024 * 8 (8 KB)
# block_size = 8192
# 1024 * 1024 * 8 (8 MiB)
# block_cache_size = 8388608
# 1024 * 1024 * 256 (256 MiB)
# max_bytes_for_level_base = 268435456
# 1024 * 1024 * 256 (256 MiB)
# max_bytes_for_level_multiplier = 268435456
# 1024 * 1024 * 64 (64 MiB)
# write_buffer_size = 67108864
# 1024 * 1024 * 64 (64 MiB)
write_buffer_size = 10737418240
# max_write_buffer_number = 4
# max_background_compactions = 2
# max_background_flushes = 2
# increase_parallelism = 3
